ServerName game-sources-apache
ServerTokens Prod
ServerSignature Off
TraceEnable Off

ProxyRequests Off
ProxyPreserveHost On
ProxyTimeout 300
AllowEncodedSlashes NoDecode

ProxyPass "/" "http://game-server:8080/" nocanon connectiontimeout=5 timeout=300
ProxyPassReverse "/" "http://game-server:8080/"

<Location "/">
    Require all granted
</Location>
